title: Enrique GARCIA
# logo: /assets/img/logo.png
description: Software Engineer and Technical Project Manager with a background in Astro(Physics).
show_downloads: false
google_analytics:
show_custom_button: true
show_personal_projects: true
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github_url: https://github.com/garciagenrique
linkedin_url: https://www.linkedin.com/in/garciagenrique/
orcid_url: https://orcid.org/0000-0003-2224-4594
email: garciag.enr@gmail.com